### ISSUE TITLE
Issue with running camViz_py 

### ISSUE THREAD

**Issue by pankhurivanjani** [JdeRobot/viz#31]
Hi,
I am facing an issue while running the camViz_py with camserver_py 
![image](https://user-images.githubusercontent.com/28755817/58451756-7737bc00-8132-11e9-80b1-0322c35de78f.png)
I think I am missing out some command..

**Comment by fqez** [comment]
Hi, make sure the client is configured correctly. It should be trying to connect to the correct ROS topic. I think it is `camserver/rgb` but I am not sure right now. You can check it with `ros topic list`.

Regards!

**Comment by pankhurivanjani** [comment]
Hello! I checked more into it and here are the updates:
1. Camserver_py + camViz tool is working perfectly. To run this I used the following commands:
     roscore
    camserver_py camserver_py.yml 
    camViz camViz.yml
2. Now, I tried to use Camserver_py + camViz_py. Commands used:
    roscore
    camserver_py camserver_py.yml
    camviz_py camviz_py.cfg 

    Result:
********************************************
pankhuri@pankhuri-LENOVO-IDEAPAD-500-15ISK:/opt/jderobot/share/jderobot/conf$ camviz_py camviz_py.cfg 
loading Ice.Config file ./camviz_py.cfg
Traceback (most recent call last):
  File "/opt/jderobot/share/jderobot/python/camViz_py/camviz.py", line 14, in <module>
    cameraProxy = jderobot.CameraPrx.checkedCast(basecameraL)
  File "/opt/jderobot/lib/python2.7/camera_ice.py", line 795, in checkedCast
    return _M_jderobot.CameraPrx.ice_checkedCast(proxy, '::jderobot::Camera', facetOrCtx, _ctx)
Ice.ConnectionRefusedException: Ice.ConnectionRefusedException:
Connection refused
!! 05/28/19 16:46:32.719 error: communicator not destroyed during global destruc
****************************************************
rostopic list:
/camserver/rgb
/rosout
/rosout_agg
I was unable to make it work.

3. I checked out the ros comm support in the camviz_py repository. 
    I edited the camViz_py.yml file by changing the 
    **Topic** from "/usb_cam/image_raw/compressed" to "/camserver/rgb"
    **Type** from "CompressedImage" to "sensor_msgs/Image"

   Now, to running it with 
    roscore
    camserver_py camserver_py.yml
    ~/viz/camViz_py$ python camViz_py.py camViz_py.yml

So, it is working with ROS now.

camserver_py is a fully ROS based component and camViz_py also supports Ros as I checked.
So, will it be a good idea to get rid of ICE Based drivers in this repo which are not useful for running with ROS1?

Regards,

**Comment by fqez** [comment]
yeah, seems like data types are not compatible (maybe image format - compressed vs no compressed images - ?) I will check this issue too :)

**Comment by pankhurivanjani** [comment]
I was getting the issue earlier, but changing the type in .yml file resolved the issue for ROS. :)

**Comment by fqez** [comment]
Nice! It would be awesome if you could make a pull request solving this issue :D Thanks a lot! Just out of curiosity.. are you working on Ubuntu 16 or 18?

Regards and good job!

**Comment by pankhurivanjani** [comment]
Thank you! :) I am working on Ubuntu 16.
Yes, I will be making a pull request to solve this issue.

**Comment by fqez** [comment]
Merged!
