### ISSUE TITLE
Refactor CarViz to work with ROS1 drivers

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/viz#37]
ROS Melodic is the reference distribution. No ICE drivers will be supported, and no JdeRobot/base dependence should be accepted anymore. The new CarViz should work nicely on a machine with a ROS1 Melodic official distribution installed from debian package.

**Comment by pankhurivanjani** [comment]
Solved by [#39 ](https://github.com/JdeRobot/viz/pull/39)
