### ISSUE TITLE
Extend CarViz to support ROS2

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/viz#38]

**Comment by pankhurivanjani** [comment]
I want to push the updated carviz tool in this repository, in a separate branch. 

This update has an interface for both ROS1 and ROS2. @jmplaza @fqez Could you please create a new branch namely 'viz-ros2' so that I can submit a PR in the same branch?

**Comment by pankhurivanjani** [comment]
Solved by [#39 ](https://github.com/JdeRobot/viz/pull/39)
